apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: three-tier-app
type: Opaque
data:
  username: cG9zdGdyZXM=  # base64 for "postgres"
  password: cGFzc3dvcmQ=  # base64 for "password"
